### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by ghost** [filtration/Bitcoin-Exchange#5]
Hi @filtration 

Please can you continue your amazing work on this project, If I may suggest maybe updating the framework to latest and maybe adding a forum?

**Comment by di48l069** [comment]
Please also provide me with the sql. If possible

**Comment by filtration** [comment]
I am re-writing this project at the moment in another framework. The `sql` file is in the root folder called exchange.sql

I personally wouldn't use this on a live server, it's buggy and not finished. I guess it's a good starting base though.
